#Welcome to our Lab practice!

This lab is all about the package, Numpy. Are you ready? Let's go!

You will find some small tasks in sections below.

> Try to figure out by yourself, or search for references. Being able to search and find information needed is an important skill that benefits you and your career for a long time.





## Import the package and rename it as np

In [3]:
# your code is here
import numpy as np

## Array Creation

### Task: Create a numpy array from a list of integers

In [3]:
# your code is here
np.random.randint(1,10,5)

array([4, 7, 1, 2, 6])

### Task: Create a numpy array of size 6, filled with zeros

In [4]:
# your code is here
np.zeros(6)

array([0., 0., 0., 0., 0., 0.])

###Task: Create a numpy array of size 6, filled with ones

In [5]:
# your code is here
np.ones(6)

array([1., 1., 1., 1., 1., 1.])

###Task: Create a numpy array with values from 0 to 10

In [6]:
# your code is here
np.arange(11)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

###Task: Create a numpy matrix of 2*3 integers, filled with zeros

In [7]:
# your code is here
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

###Task: Create a numpy matrix of 3*2 integers, filled with ones

In [8]:
# your code is here
np.ones((3,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

###Task: Create a numpy matrix of 3*2 integers, filled with random integers in [0, 10]

In [9]:
# your code is here
np.random.randint(0,10,(3,2))

array([[1, 6],
       [9, 7],
       [4, 2]])

###Task: Create a numpy matrix of 100 * 2, filled with random float value in [0, 1]

In [10]:
# your code is here
np.random.rand(100,2)

array([[0.12129769, 0.30718248],
       [0.59704457, 0.83125065],
       [0.74388375, 0.18171717],
       [0.87324776, 0.282205  ],
       [0.41877575, 0.64468239],
       [0.18893968, 0.45433499],
       [0.98519579, 0.03098539],
       [0.16643871, 0.30031663],
       [0.52330758, 0.97441374],
       [0.99506317, 0.7012603 ],
       [0.90887859, 0.66844601],
       [0.58658193, 0.3869856 ],
       [0.39541155, 0.7802116 ],
       [0.562426  , 0.5098985 ],
       [0.34983164, 0.52322773],
       [0.54342062, 0.37317506],
       [0.58481846, 0.81678872],
       [0.83777786, 0.81859844],
       [0.44098528, 0.15244553],
       [0.86491152, 0.30297378],
       [0.57871488, 0.86041368],
       [0.84768185, 0.54595427],
       [0.71077084, 0.69502756],
       [0.60290948, 0.6449227 ],
       [0.71220086, 0.01230805],
       [0.571532  , 0.73841971],
       [0.50091309, 0.34746118],
       [0.74843577, 0.54508917],
       [0.08788789, 0.05998464],
       [0.34858174, 0.79724977],
       [0.

###Task: Create a numpy matrix of 2 * 3 * 4, filled with integers from 1 to 24.

In [11]:
# your code is here
np.random.randint(1,25,(2,3,4))

array([[[ 2, 20, 16,  8],
        [ 1,  1,  8, 13],
        [ 2,  7, 17,  5]],

       [[ 9, 15,  7,  6],
        [21, 22, 19, 15],
        [15, 20, 23, 24]]])

## Array Indexing

### Task: Let X be a numpy array, and X = np.array([1, 2, 3, 4, 5])

In [13]:
# your code is here
X = np.array([1, 2, 3, 4, 5])
X

array([1, 2, 3, 4, 5])

### Task: Show the first element of X

In [14]:
# your code is here
X[0]

np.int64(1)

### Task: Show the last element of X

In [15]:
# your code is here
X[-1]

np.int64(5)

### Task: Show the first 3 elements of X

In [17]:
# your code is here
X[:3]

array([1, 2, 3])

###Task: Show the last 3 elements of X

In [19]:
# your code is here
X[-3:]

array([3, 4, 5])

###Task: Show the elements of X whose index is odd (1, 3, 5, ...)

In [20]:
# your code is here
X[1::2]

array([2, 4])

###Task: Show the elements of X except the last one

In [22]:
# your code is here
X[:-1]

array([1, 2, 3, 4])

### Task: Let X be a numpy matrix with dimension 3 * 4, and filled from 0 to 11.

In [23]:
# your code is here
X = np.arange(12).reshape(3,4)
X

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

###Task: Show the first row of X

In [24]:
# your code is here
X[0]

array([0, 1, 2, 3])

###Task: Show the first column of X

In [25]:
# your code is here
X[:,0]

array([0, 4, 8])

###Task: Show the first element of the first row of X

In [26]:
# your code is here
X[0,0]

np.int64(0)

###Task: Show the last row of X

In [28]:
# your code is here
X[-1]

array([ 8,  9, 10, 11])

###Task: Show the last column of X

In [29]:
# your code is here
X[:,-1]

array([ 3,  7, 11])

###Task: Show the last element of the last row of X

In [30]:
# your code is here
X[-1,-1]

np.int64(11)

###Task: Show all the rows except the last row of X

In [31]:
# your code is here
X[:-1]

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

###Task: Show all the columns except the last column of X

In [32]:
# your code is here
X[:,:-1]

array([[ 0,  1,  2],
       [ 4,  5,  6],
       [ 8,  9, 10]])

### Task: Show the first two elements of the first two rows

In [33]:
# your code is here
X[:2,:2]

array([[0, 1],
       [4, 5]])

## Array Statistics

###Task: Create a numpy array X, print the sum, mean, std, var, max, min of it

In [38]:
# your code is here
X = np.arange(10)
X
X.sum(), X.mean(), X.std(), X.var(), X.max(), X.min()

(np.int64(45),
 np.float64(4.5),
 np.float64(2.8722813232690143),
 np.float64(8.25),
 np.int64(9),
 np.int64(0))

###Task: Create a numpy matrix X as n * m, print the sum, mean, std, var, max, min of the 1st row of it.

In [14]:
# your code is here

# Set matrix size
n, m = 4, 5  # example dimensions

# Create the matrix
X = np.random.rand(n, m)  # random values between 0 and 1

# First column
first_col = X[:, 0]

# Compute statistics
print("Matrix X:\n", X)
print("First column:", first_col)
print("Sum:", np.sum(first_col))
print("Mean:", np.mean(first_col))
print("Standard Deviation:", np.std(first_col))
print("Variance:", np.var(first_col))
print("Max:", np.max(first_col))
print("Min:", np.min(first_col))


Matrix X:
 [[0.33524047 0.04003867 0.09050376 0.38374511 0.81646423]
 [0.74887305 0.93368662 0.19080163 0.22909315 0.25932088]
 [0.4960111  0.25473036 0.25083149 0.66187226 0.2755273 ]
 [0.33474996 0.20168359 0.52325004 0.84692376 0.73990626]]
First column: [0.33524047 0.74887305 0.4960111  0.33474996]
Sum: 1.9148745752736698
Mean: 0.47871864381841744
Standard Deviation: 0.16925971349161859
Variance: 0.028648850611264813
Max: 0.7488730523348439
Min: 0.3347499578397388


###Task: Create a numpy matrix X as n * m, print the sum, mean, std, var, max, min of the 1st column of it.

In [13]:
# your code is here
# Create a sample matrix
X = np.random.randint(1, 10, (3, 4))
print("Matrix X:\n", X)

# Extract the first column
first_col = X[:, 0]

# Compute statistics on the first column
print("First column:", first_col)
print("Sum:", np.sum(first_col))
print("Mean:", np.mean(first_col))
print("Standard Deviation:", np.std(first_col))
print("Variance:", np.var(first_col))
print("Max:", np.max(first_col))
print("Min:", np.min(first_col))



Matrix X:
 [[9 2 4 2]
 [2 4 5 4]
 [3 3 1 1]]
First column: [9 2 3]
Sum: 14
Mean: 4.666666666666667
Standard Deviation: 3.0912061651652345
Variance: 9.555555555555555
Max: 9
Min: 2


## Array Linear Algebra

###Task: Create two numpy matrix X with 2 * 2, and Y with 2 * 2. Practice Linear Algebra operations, such as +, -, *, .T, @, etc.

In [15]:
# your code is here


# Create two 2x2 matrices
X = np.array([[1, 2],
              [3, 4]])

Y = np.array([[5, 6],
              [7, 8]])

# Linear algebra operations
print("Matrix X:\n", X)
print("Matrix Y:\n", Y)

print("\nAddition (X + Y):\n", X + Y)
print("Subtraction (X - Y):\n", X - Y)
print("Element-wise Multiplication (X * Y):\n", X * Y)
print("Transpose of X (X.T):\n", X.T)
print("Transpose of Y (Y.T):\n", Y.T)
print("Matrix Multiplication (X @ Y):\n", X @ Y)
print("Matrix Multiplication (np.dot(X, Y)):\n", np.dot(X, Y))


Matrix X:
 [[1 2]
 [3 4]]
Matrix Y:
 [[5 6]
 [7 8]]

Addition (X + Y):
 [[ 6  8]
 [10 12]]
Subtraction (X - Y):
 [[-4 -4]
 [-4 -4]]
Element-wise Multiplication (X * Y):
 [[ 5 12]
 [21 32]]
Transpose of X (X.T):
 [[1 3]
 [2 4]]
Transpose of Y (Y.T):
 [[5 7]
 [6 8]]
Matrix Multiplication (X @ Y):
 [[19 22]
 [43 50]]
Matrix Multiplication (np.dot(X, Y)):
 [[19 22]
 [43 50]]
