# Introduction

Now we have learned all the basic knowledge needed to utilize powerful Python packages for Data Science. We start with the NumPy (Numerical Python) package. Numpy is one of the core packages for numerical computing in Python.

Let's get started!

In [1]:
# Let's import the package

import numpy as np

# Basic Arrays

In [2]:
np.array([0, 1, 2, 3])

array([0, 1, 2, 3])

In [3]:
a = np.array([0, 1, 2, 3])
type(a)

numpy.ndarray

In [4]:
a.shape

(4,)

In [11]:
a[0]

np.int64(0)

In [12]:
a[3]

np.int64(3)

In [7]:
a[4]

IndexError: index 4 is out of bounds for axis 0 with size 4

In [8]:
a[-1]

np.int64(3)

In [13]:
a[-4]

np.int64(0)

In [10]:
a[-5]

IndexError: index -5 is out of bounds for axis 0 with size 4

In [14]:
a[0:]

array([0, 1, 2, 3])

In [15]:
a[1:]

array([1, 2, 3])

In [16]:
a[:1]

array([0])

In [17]:
a[[-1]]

array([3])

In [18]:
a[:-1]

array([0, 1, 2])

In [19]:
a[::2]

array([0, 2])

In [20]:
a[1::2]

array([1, 3])

# Array Types

In [21]:
a = np.array([0, 1, 2, 3])
b = np.array([0.0, 0.1, 0.2, 0.3])

In [22]:
type(a)

numpy.ndarray

In [23]:
a.dtype

dtype('int64')

In [24]:
type(b)

numpy.ndarray

In [25]:
b.dtype

dtype('float64')

In [26]:
c = np.array([0, 1.1, 2, 3.8], dtype = float)
c

array([0. , 1.1, 2. , 3.8])

In [27]:
c.dtype

dtype('float64')

In [28]:
d = np.array([0, 1.1, 2, 3.8], dtype = int)
d

array([0, 1, 2, 3])

In [29]:
d.dtype

dtype('int64')

# Dimensions and Shapes

In [30]:
a = np.array([0, 1, 2, 3])

In [31]:
a.shape

(4,)

In [32]:
A = np.array([
    [0, 1, 2, 3],
    [4, 5, 6, 7],
    [8, 9, 10, 11]
])
A

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [33]:
A.shape

(3, 4)

In [34]:
B = np.array([
    [
     [0, 1],
     [2, 3],
     [4, 5]
    ],
    [

     [6, 7],
     [8, 9],
     [10, 11]
    ]
])
B

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]]])

In [35]:
B.shape

(2, 3, 2)

In [36]:
B.ndim

3

In [37]:
B.size

12

# Indexing and Slicing of Matrices

In [38]:
A = np.array([
    [0, 1, 2, 3],
    [4, 5, 6, 7]
])
A

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [39]:
A.shape

(2, 4)

In [40]:
A[0]

array([0, 1, 2, 3])

In [41]:
A[1]

array([4, 5, 6, 7])

In [42]:
A[:0]

array([], shape=(0, 4), dtype=int64)

In [43]:
A[:1]

array([[0, 1, 2, 3]])

In [44]:
A[:,0]

array([0, 4])

In [45]:
A[:,3]

array([3, 7])

In [46]:
A[0,0]

np.int64(0)

In [48]:
A[1, 3]

np.int64(7)

In [49]:
A[:,1:3]

array([[1, 2],
       [5, 6]])

In [50]:
A[0] = np.array([8, 9, 10, 11])
A

array([[ 8,  9, 10, 11],
       [ 4,  5,  6,  7]])

In [51]:
A[1] = 98
A

array([[ 8,  9, 10, 11],
       [98, 98, 98, 98]])

# Statistics

In [52]:
a = np.array([0, 1, 2, 4])
a

array([0, 1, 2, 4])

In [53]:
a.sum()

np.int64(7)

In [54]:
a.mean()

np.float64(1.75)

In [55]:
a.std()

np.float64(1.479019945774904)

In [56]:
a.var()

np.float64(2.1875)

In [57]:
a.max()

np.int64(4)

In [58]:
a.min()

np.int64(0)

In [59]:
A = np.array([
     [0, 1, 2, 3],
     [4, 5, 6, 7],
     [8, 9, 10 , 11]
])
A

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [60]:
A.sum()

np.int64(66)

In [61]:
A.mean()

np.float64(5.5)

In [62]:
A.std()

np.float64(3.452052529534663)

In [63]:
A.var()

np.float64(11.916666666666666)

In [64]:
A.max()

np.int64(11)

In [65]:
A.min()

np.int64(0)

In [66]:
A.sum(axis=0)

array([12, 15, 18, 21])

In [ ]:
A.sum(axis=1)

array([ 6, 22, 38])

In [67]:
A.mean(axis=0)

array([4., 5., 6., 7.])

In [68]:
A.max(axis = 1)

array([ 3,  7, 11])

# Linear Algebra

In [69]:
A = np.array([
    [0, 1, 2],
    [3, 4, 5]
])

B = np.array([
    [6, 7, 8],
    [9, 10, 11]
])

In [70]:
A

array([[0, 1, 2],
       [3, 4, 5]])

In [71]:
B

array([[ 6,  7,  8],
       [ 9, 10, 11]])

In [72]:
A + B

array([[ 6,  8, 10],
       [12, 14, 16]])

In [73]:
A - B

array([[-6, -6, -6],
       [-6, -6, -6]])

In [74]:
A * B

array([[ 0,  7, 16],
       [27, 40, 55]])

In [75]:
B.T

array([[ 6,  9],
       [ 7, 10],
       [ 8, 11]])

In [76]:
A @ (B.T)

array([[ 23,  32],
       [ 86, 122]])

In [77]:
A.T @ B

array([[27, 30, 33],
       [42, 47, 52],
       [57, 64, 71]])

# Useful functions

In [78]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [79]:
np.arange(5, 10)

array([5, 6, 7, 8, 9])

In [80]:
np.arange(5, 10, 2)

array([5, 7, 9])

In [81]:
np.arange(5, 10, 0.5)

array([5. , 5.5, 6. , 6.5, 7. , 7.5, 8. , 8.5, 9. , 9.5])

In [82]:
np.arange(10).reshape(5,2)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [83]:
np.arange(12).reshape(3, 4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [84]:
np.random.randint(0, 10, (10))

array([5, 3, 0, 5, 7, 3, 1, 0, 6, 8])

In [85]:
np.random.randint(0, 10, (5, 2))

array([[3, 6],
       [6, 7],
       [0, 8],
       [4, 9],
       [8, 0]])

In [86]:
np.random.rand(2, 4)

array([[0.93283407, 0.11092866, 0.7474047 , 0.76026215],
       [0.08326653, 0.17641501, 0.30148123, 0.18467391]])

In [87]:
np.random.normal(0, 0.1, (10))

array([-0.01275835,  0.03250908,  0.05295081,  0.00450117,  0.0328069 ,
       -0.08833749, -0.00407834, -0.00180817, -0.07318607, -0.05993113])

In [88]:
np.random.normal(0, 0.1, (2, 5))

array([[-0.16400692,  0.04187616,  0.04458931,  0.04549415,  0.11795989],
       [ 0.0165946 , -0.15873483, -0.00493359,  0.03857514, -0.08540642]])

In [89]:
np.random.uniform(0, 1, (3, 4))

array([[0.57145234, 0.12484536, 0.48760296, 0.22976351],
       [0.39304278, 0.78427719, 0.43777112, 0.76563037],
       [0.87186011, 0.63722943, 0.60090698, 0.54205879]])

In [90]:
a = np.random.uniform(0, 1, (2, 5))
np.sort(a)

array([[0.22260937, 0.39045172, 0.88980567, 0.91368481, 0.97141572],
       [0.16859141, 0.33429076, 0.38522636, 0.69773032, 0.71362267]])

In [91]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [92]:
np.ones((2, 3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [93]:
np.ones((2, 5), dtype = int)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])